govconnect/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import login_page
from .views import RegisterHelpView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", login_page, name="user-login"),
    path("help/register/", RegisterHelpView.as_view(), name="register-help"),
    path("account/", include("users.urls")),
    path("service/", include("services.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

govconnect/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path("", views.UserHomeView.as_view(), name="user-home"),
    path("auth/", views.two_step_verification, name="user-auth"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logout.html", next_page="/"),
        name="user-logout",
    ),
    path("settings/", views.UserSettingsView.as_view(), name="user-settings"),
    path("settings/update/services", views.update_enabled_services, name="user-update-enabled-services"),
]

govconnect/users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import GovConnectUserManager


class GovConnectUser(AbstractBaseUser, PermissionsMixin):
    class IDType(models.TextChoices):
        """Enum for ID Types"""

        DRIVER_LICENSE = "DL", _("Driver License")
        MARINE_LICENSE_INDICATOR = "ML", _("Marine License")
        PASSPORT = "PP", _("Passport")
        BIRTH_CERTIFICATE = "BC", _("Birth Certificate")
        PROOF_OF_AGE_CARD = "POA", _("Proof of Age Card")
        PHOTO_IDENTIFICATION_CARD = "PIC", _("Photo Identification Card")

    class StateOptions(models.TextChoices):
        AUSTRALIAN_CAPITAL_TERRITORY = "ACT", _("Australian Capital Territory")
        NEW_SOUTH_WALES = "NSW", _("New South Wales")
        NORTH_TERRITORY = "NT", _("North Territory")
        SOUTHERN_AUSTRALIA = "SA", _("Southern Australia")
        TASMANIA = "TAS", _("Tasmania")
        VICTORIA = "VIC", _("Victoria")
        QUEENSLAND = "QLD", _("Queensland")
        WESTERN_AUSTRALIA = "WA", _("Western Australia")

    # == Mandatory Information ==
    email = models.EmailField(_("Email Address"), unique=True)
    phone_number = models.CharField(_("Phone Number"), max_length=20, unique=True, null=True, blank=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    other_names = ArrayField(models.CharField(max_length=150), blank=True, null=True)
    date_of_birth = models.DateField()
    street_address = models.CharField(max_length=150)
    suburb = models.CharField(max_length=150)
    state = models.CharField(max_length=3, choices=StateOptions.choices)
    postcode = models.IntegerField()
    address = models.CharField(max_length=150)

    # == Identification Information -> Also Mandatory ==
    primary_identification = models.CharField(
        max_length=3, choices=IDType.choices, default=IDType.DRIVER_LICENSE
    )
    # Effectively The User's Password, however the user must complete a 2FA to be authenticated
    primary_identification_number = models.CharField(max_length=50, unique=True)
    # E.g. [['ID Type', 'ID Number'], ['PP', '123456789']]
    other_identities = ArrayField(ArrayField(models.CharField(max_length=50), size=2), null=True, blank=True)

    # The 'Your Data' page will show services are storing the users information, and what information they have.
    # E.g.
    #  [
    #    ["Service ID 1", "Service Full Name 1", "Service Link 1",
    #      ["The information they have 1"]
    #    ],
    #    ["Service ID 2", "Service Full Name 2", "Service Link 2",
    #      ["The information they have 2"]
    #    ]
    #  ]
    services_that_have_your_data = ArrayField(
        ArrayField(models.CharField(max_length=150)), blank=True, null=True
    )

    # == Other Information ==
    date_created = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=False)
    last_login = models.DateTimeField(default=timezone.now, null=True, blank=True)
    last_login_ip = models.GenericIPAddressField(null=True, blank=True)

    # Password isn't needed
    password = None

    # == MultiFactor Authentication ==
    # The user MUST use a type of MFA to login
    # By default, the secret question will be used for authentication
    # Secret Questions will be chosen/created by the user to provide an extra layer of security, however premade questions are provided
    secret_question = models.CharField(max_length=150)
    # Answers will be hashed and stored in the database
    secret_question_answer = models.CharField(max_length=150)
    # Sends SMS one-time password
    sms_one_time_password = models.BooleanField(default=False)
    # Sends Email One-Time Password
    email_one_time_password = models.BooleanField(default=False)
    # Uses a One-time Password Generator
    one_time_generator = models.BooleanField(default=False)
    # Uses FIDO Passwordless Authentication
    passwordless_login = models.BooleanField(default=False)
    # Uses a physical security device to authenticate the user
    physical_security_authentication = models.BooleanField(default=False)

    # == Permissions ==
    is_staff = models.BooleanField(default=False)

    # == Define Custom Manager ==
    objects = GovConnectUserManager()

    # == Fields Required for Account Creation ==
    USERNAME_FIELD = "primary_identification_number"
    REQUIRED_FIELDS = [
        "email",
        "phone_number",
        "first_name",
        "last_name",
        "date_of_birth",
        "street_address",
        "suburb",
        "state",
        "postcode",
        "secret_question",
        "secret_question_answer",
        "primary_identification",
    ]

    def save(self, *args, **kwargs):
        self.address = f"{self.street_address}, {self.suburb} {self.state} {self.postcode}"
        super(GovConnectUser, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class EnabledServices(models.Model):
    """
    The EnabledServices model contains the data for which services users have enabled
    This will determine which services are searchable by the user
    """

    user = models.ForeignKey(GovConnectUser, on_delete=models.CASCADE)
    # {"service_name": True}, {"service_name": False}, etc.
    services = models.JSONField(
        default={"Federal": {"Centrelink": False, "Child Support": False, "Medicare": False}}
    )

    def __str__(self):
        return f"{self.user.last_name}, {self.user.first_name}"

govconnect/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from .models import GovConnectUser, EnabledServices

id_choices = [
    ("", _("Select an ID type")),
    ("DL", _("Driving License")),
    ("ML", _("Marine License")),
    ("PP", _("Passport")),
    ("BC", _("Birth Certificate")),
    ("POA", _("Proof of Age Card")),
    ("PIC", _("Photo Identification Card")),
]


class GovConnectAuthenticationForm(AuthenticationForm):
    """Custom User Authentication Form for GovConnect"""

    password = None  # Remove password field from form

    id_type = forms.CharField(
        label=_("Primary Identification Type"),
        max_length=50,
        widget=forms.Select(choices=id_choices),
    )
    username = forms.CharField(
        label=_("Primary Identification Number"),
        max_length=50,
        widget=forms.TextInput(attrs={"placeholder": "License No. / CRN", "autofocus": True}),
    )
    date_of_birth = forms.DateField(label=_("Date of Birth"), widget=forms.DateInput(attrs={"type": "date"}))


class GovConnect2FactorAuthenticationForm(forms.ModelForm):
    secret_question_answer = forms.CharField(
        label=_("Secret Question"),
        max_length=150,
        help_text=_("Enter the answer to your secret question"),
        widget=forms.Textarea(
            attrs={
                "autofocus": True,
                "required": True,
                "placeholder": "The answer to your secret question...",
                "autocomplete": "off",
            }
        ),
    )

    class Meta:
        model = GovConnectUser
        fields = ("secret_question_answer",)


class UpdateGovConnectUserForm(forms.ModelForm):
    class Meta:
        model = GovConnectUser
        # The MFA items will be modified in a different view
        # since they require setup outside of the form
        # They are in this form to show their status
        fields = [
            "primary_identification",
            "primary_identification_number",
            "email",
            "phone_number",
            "street_address",
            "suburb",
            "state",
            "postcode",
            "sms_one_time_password",
            "email_one_time_password",
            "one_time_generator",
            "passwordless_login",
            "physical_security_authentication",
        ]

govconnect/users/views.py
from json import loads

from asgiref.sync import sync_to_async
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.hashers import check_password
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import UpdateView
from django.views.generic.list import MultipleObjectMixin

from services.models import QueenslandService
from .backends import GovConnectUserAuthenticationBackend
from .forms import GovConnect2FactorAuthenticationForm, GovConnectAuthenticationForm, UpdateGovConnectUserForm
from .models import EnabledServices, GovConnectUser


#! Convert to Class Based View
def login_page(request):
    form = GovConnectAuthenticationForm()
    context = {"form": form}

    if request.method == "POST":
        form = GovConnectAuthenticationForm(request.POST)

        user = GovConnectUserAuthenticationBackend().authenticate(
            request,
            id_type=request.POST["id_type"],
            id_num=request.POST["username"],
            date_of_birth=request.POST["date_of_birth"],
        )

        if user is not None:
            request.session["pk"] = user.pk
            return redirect("user-auth")

        else:
            messages.error(request, "Invalid login details")
            return render(request, "users/login.html", {"form": form})

    return render(request, "users/login.html", context)


#! Convert to Class Based View
def two_step_verification(request):
    form = GovConnect2FactorAuthenticationForm(request.POST)
    pk = request.session.get("pk")

    if pk:
        # Will add ways for other methods of authentication
        # Flags for other MFA types will be used to check this.
        user = GovConnectUser.objects.get(pk=pk)
        answer_hash = user.secret_question_answer

        if not request.POST:
            # If using other 2-factor authentication methods,
            # this would be where the code would be, but it hasn't been created yet
            pass

        if form.is_valid():
            answer = form.cleaned_data.get("secret_question_answer")
            if check_password(answer, answer_hash):
                login(request, user)
                return redirect("user-home")
            else:
                return redirect("user-login")
    else:
        return redirect("user-login")

    return render(
        request,
        "users/two_step_verification.html",
        context={"form": form, "question": user.secret_question},
    )


# class UserHomeView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
# class UserHomeView(LoginRequiredMixin, UserPassesTestMixin, MultipleObjectMixin, ListView):
# ? Needs to be Detail View and List View
# ? For User details and the search box respectively
class UserHomeView(LoginRequiredMixin, DetailView):
    template = "users/user_home.html"
    model = GovConnectUser

    def get(self, request):
        return render(request, "users/account.html")


class UserSettingsView(LoginRequiredMixin, UpdateView):
    model = GovConnectUser
    form_class = UpdateGovConnectUserForm
    template = "users/settings.html"

    def get(self, request, *args, **kwargs):
        services = EnabledServices.objects.get(user=request.user).services
        federal = {key: value for key, value in sorted(services["Federal"].items())}
        state = {key: value for key, value in sorted(services["State"].items())}
        form = self.form_class(instance=request.user)

        return render(
            request,
            self.template,
            context={"form": form, "federal_services": federal, "state_services": state},
        )

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=request.user)
        services = EnabledServices.objects.get(user=request.user).services
        federal = {key: value for key, value in sorted(services["Federal"].items())}
        state = {key: value for key, value in sorted(services["State"].items())}

        if form.is_valid():
            form.save()
            messages.success(request, "Your details have been updated successfully!")
            return redirect("user-settings")

        messages.error(request, "There was an error updating your details.")
        return render(
            request, self.template, context={"form": form, "federal_services": federal, "state_services": state}
        )


def update_enabled_services(request, *args, **kwargs):
    es = EnabledServices.objects.get(user=request.user)
    services_enabled_by_user = es.services
    enabled = {name: True if value == "on" else False for name, value in request.POST.items()}
    del enabled["csrfmiddlewaretoken"]

    for service_region in services_enabled_by_user:
        for service, value in services_enabled_by_user[service_region].items():
            # Checks if the service is currently enabled by the user, but is not in the request
            # Therefore, the user has opted out of the service
            if service not in enabled and value:
                services_enabled_by_user[service_region][service] = False

            # Checks if the service is currently disabled by the user, but is in the request
            elif service in enabled and value != enabled[service]:
                services_enabled_by_user[service_region][service] = enabled[service]

    es.services = services_enabled_by_user
    es.save()
    messages.success(request, "Your service preferences have been updated successfully!")
    return redirect("user-settings")


# API Endpoint for service searching
@sync_to_async
def search_services(request):
    if request.method == "POST":
        search_term = loads(request.body).get("search_term").rstrip()
        if search_term:
            # Gets services enabled by the user
            enabled_services = EnabledServices.objects.get(user=request.user).services
            federal_enabled = [slugify(s) for s, v in enabled_services["Federal"].items() if v]
            state_enabled = [slugify(s) for s, v in enabled_services["State"].items() if v]

            if request.user.state == "ACT":
                pass

            elif request.user.state == "NSW":
                pass

            elif request.user.state == "NT":
                pass

            elif request.user.state == "SA":
                pass

            elif request.user.state == "TAS":
                pass

            elif request.user.state == "VIC":
                pass

            elif request.user.state == "QLD":
                # Queries the database for services that match the search term
                results = QueenslandService.objects.filter(name__icontains=search_term)

            elif request.user.state == "WA":
                pass

            # Filters the results to only include services that are enabled by the user
            results = (
                (
                    results.filter(category_slug__in=federal_enabled)
                    | results.filter(category_slug__in=state_enabled)
                )
                .values_list("name", "category", "description", "url")
                .distinct()
                .order_by("category")
            )
            data = list(results.values())

            # Returns results as a JSON object, to be parsed in JS
            return JsonResponse(data, safe=False)

govconnect/templates/users/account.html
{% extends "base.html" %}
{% if not user.is_authenticated %}
<script>
    window.location.href = "{% url 'user-login' %}";
</script>
{% endif %}
{% block content %}
<section id="account_home">
    <div class="left">
        <div id="username">
            <h1>Welcome {{ user.first_name }} {{ user.last_name }}</h1>
        </div>
        <div id="details">
            <h2>Your Details</h2>
            <hr />
            <table>
                <tr>
                    <td>Address:</td>
                    <td>{{ user.address }}</td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <td>Contact Number:</td>
                    <td>{{ user.phone_number }}</td>
                </tr>
                <tr>
                    <td>Date of Birth:</td>
                    <td>{{ user.date_of_birth|date:'d/m/Y' }}</td>
                </tr>
            </table>
        </div>
        <div id="recent-activity">
            <h2>Linked Services with Recent Activity</h2>
            <hr />
            <div class="recent">
                <h3>Certificate of Affect <a href="/form/#"><i class="bi bi-arrow-up-right"></i></a></h3>
                <hr />
                <div class="recent-info">
                    <div class="recent-detail">
                        <div class="recent-left">
                            <div>
                                <div><strong>Address:</strong></div>
                                <div>138 Flinders Parade, Sandgate</div>
                            </div>
                            <div>
                                <div><strong>LGA:</strong></div>
                                <div>Brisbane City Council</div>
                            </div>
                        </div>
                        <div class="recent-right">
                            <div>
                                <div><strong>Registration Status:</strong></div>
                                <div>Entered</div>
                            </div>
                            <div>
                                <div><strong>Classification:</strong></div>
                                <div>State Heritage</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="recent">
                <div class="recent-info">
                    <h3>Driver's License <a href="/form/#"><i class="bi bi-arrow-up-right"></i></a></h3>
                    <hr />
                    <div class="recent-detail">
                        <div class="recent-left">
                            <div>
                                <div><strong>License No.:</strong></div>
                                <div>000 000 000</div>
                            </div>
                            <div>
                                <div><strong>License Category/Type:</strong></div>
                                <div>CA/O</div>
                            </div>
                        </div>
                        <div class="recent-right">
                            <div>
                                <div><strong>Effective:</strong></div>
                                <div>21.08.2016</div>
                            </div>
                            <div>
                                <div><strong>Expiry</strong></div>
                                <div>21.08.2021</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="vl">
    </div>
    <div class="right">
        <div id="service-search">
            <div id="search">
                <h1>Search for services</h1>
                <form class="search_area">
                    <input type="text" id="searchField" placeholder="Search for services..." autocomplete="off" />
                    <button type="submit"><i class="bi bi-search"></i></button>
                </form>
            </div>
            <div class="search_results" id="searchResults"></div>
        </div>
        <div class="recommended_services" id="recommendedServices">
            <h1>Recommended Services</h1>
            <h2>These services are tailored to you based on activity on your account.</h2>
            <ul>
                <li>Apply for a senior card</li>
                <li>Renew drivers licence</li>
                <li>Apply for carer card</li>
                <li>Register as voter</li>
                <li>Report fire ants</li>
                <li>Renew fishing licence</li>
            </ul>
        </div>
    </div>
</section>
{% endblock content %}

govconnect/templates/users/logout.html
{% extends "base.html" %}

govconnect/templates/users/settings.html
{% extends "base.html" %}
{% block content %}
<section id="user_settings">
    <div class="title">
        <h1>Your Account</h1>
        <hr />
    </div>
    <div class="forms">
        <form method="POST" action="{% url 'user-update-enabled-services' %}" class="opt-in-services">
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            <div class="opt-title">
                <span class="opt-title-text">
                    <h2>Opt-in Services</h2>
                    <span class="subtitle">
                        Select services you would like to have access to
                        <i class="bi bi-question-circle"
                            data-tooltip="Only services that you have opted into will appear in your searches"></i>
                    </span>
                </span>
                <button type="submit">Update</button>
            </div>
            <h3>Federal Services</h3>
            <hr />
            <div class="federal">
                {% for service, value in federal_services.items %}
                <div class="service">
                    {{ service }}
                    <span class="switch">
                        <input type="checkbox" id="{{ service }}" {% if value %}checked{% endif %}
                            name="{{ service }}" />
                        <label for="{{ service }}"></label>
                    </span>
                </div>
                {% endfor %}
            </div>
            <h3>State Services</h3>
            <hr />
            <div class="state">
                {% for service, value in state_services.items %}
                <div class="service">
                    {{ service }}
                    <span class="switch">
                        <input type="checkbox" id="{{ service }}" {% if value %}checked{% endif %}
                            name="{{ service }}" />
                        <label for="{{ service }}"></label>
                    </span>
                </div>
                {% endfor %}
            </div>
        </form>
        <div class="vl"></div>
        <form method="POST" class="account-settings">
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endif %}
            <h2>Account Settings</h2>
            {% csrf_token %}
            <div class="form_items">
                <div class="form_section">
                    <h4>Form of Identification for Sign In</h4>
                    {{ form.primary_identification }}
                    {{ form.primary_identification_number }}
                </div>

                <div class="form_section">
                    <h4>Update Contact Information</h4>
                    <div class="form_group">
                        <label for="id_email">{{ form.email.label }}&nbsp;&nbsp;</label>
                        {{ form.email }}
                    </div>

                    <div class="form_group">
                        <label for="id_phone_number">
                            {{ form.phone_number.label }}
                        </label>
                        {{ form.phone_number }}
                    </div>
                </div>

                <div class="form_section">
                    <h4>Update Address</h4>
                    <div class="form_group">
                        <label for="id_street_address">
                            {{ form.street_address.label }}
                        </label>
                        {{ form.street_address }}
                    </div>
                    <div class="form_group">
                        <label for="id_suburb">{{ form.suburb.label }}
                        </label>
                        {{ form.suburb }}
                    </div>
                    <div class="form_group">
                        <label for="id_state">
                            {{ form.state.label }}
                        </label>
                        {{ form.state }}
                    </div>
                    <div class="form_group">
                        <label for="id_postcode">
                            {{ form.postcode.label }}
                        </label>
                        {{ form.postcode }}
                    </div>
                </div>

                <div class="form_section" id="mfa">
                    <h4>Multi-factor Authentication</h4>
                    <div class="form_group">
                        <label for="id_sms_one_time_password">{{ form.sms_one_time_password.label }}</label>
                        <div class="form_sub_group">
                            {% if form.sms_one_time_password.value == "on" %}
                            <span class="mfa enabled">Enabled <i class="bi bi-check-circle"></i></span>
                            {% else %}
                            <span class="mfa disabled">Disabled <i class="bi bi-x-circle"></i></span>
                            <a class="mfa setup" href="/account/settings/setup/sms-otp/">
                                Setup <i class="bi bi-arrow-up-right-circle"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form_group">
                        <label for="id_email_one_time_password">{{ form.email_one_time_password.label }}</label>
                        <div class="form_sub_group">
                            {% if form.email_one_time_password.value == "on" %}
                            <span class="mfa enabled">Enabled <i class="bi bi-check-circle"></i></span>
                            {% else %}
                            <span class="mfa disabled">Disabled <i class="bi bi-x-circle"></i></span>
                            <a class="mfa setup" href="/account/settings/setup/email-otp/">
                                Setup <i class="bi bi-arrow-up-right-circle"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form_group">
                        <label for="id_one_time_generator">{{ form.one_time_generator.label}}</label>
                        <div class="form_sub_group">
                            {% if form.one_time_generator.value == "on" %}
                            <span class="mfa enabled">Enabled <i class="bi bi-check-circle"></i></span>
                            {% else %}
                            <span class="mfa disabled">Disabled <i class="bi bi-x-circle"></i></span>
                            <a class="mfa setup" href="/account/settings/setup/otp/">
                                Setup <i class="bi bi-arrow-up-right-circle"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form_group">
                        <label for="id_passwordless_login">{{ form.passwordless_login.label }}</label>
                        <div class="form_sub_group">
                            {% if form.passwordless_login.value == "on" %}
                            <span class="mfa enabled">Enabled <i class="bi bi-check-circle"></i></span>
                            {% else %}
                            <span class="mfa disabled">Disabled <i class="bi bi-x-circle"></i></span>
                            <a class="mfa setup" href="/account/settings/setup/passwordless/">
                                Setup <i class="bi bi-arrow-up-right-circle"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form_group">
                        <label for="id_physical_security_authentication">
                            {{ form.physical_security_authentication.label}}
                        </label>
                        <div class="form_sub_group">
                            {% if form.physical_security_authentication.value == "on" %}
                            <span class="mfa enabled">Enabled <i class="bi bi-check-circle"></i></span>
                            {% else %}
                            <span class="mfa disabled">Disabled <i class="bi bi-x-circle"></i></span>
                            <a class="mfa setup" href="/account/settings/setup/physical/">
                                Setup <i class="bi bi-arrow-up-right-circle"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>

                </div>
                <button type="submit" class="update-details">Update Details</button>
            </div>
        </form>
    </div>
    <hr style="margin-top: 1rem; margin-bottom: 0.5rem;" />
</section>
{% endblock content%}